@sourceRepoUrl = https://github.com/my-org/my-source-repo
@sourceBranchName = main
@targetRepo = my-org/my-target-repo
@eventType = event_type
@installationId = 12345678
@subscriptionId = 1

### Create subscription
POST http://localhost:3000/subscriptions
Content-Type: application/json

{
  "source_repo_url": "{{sourceRepoUrl}}",
  "source_branch_name": "{{sourceBranchName}}",
  "target_repo": "{{targetRepo}}",
  "event_type": "{{eventType}}",
  "gh_app_installation_id": {{installationId}}
}

### List subscriptions
GET http://localhost:3000/subscriptions

### Get subscription
GET http://localhost:3000/subscriptions/{{subscriptionId}}

### Update subscription
PATCH http://localhost:3000/subscriptions/{{subscriptionId}}
Content-Type: application/json

{
  "target_repo": "my-org/new-target-repo"
}

### Delete subscription
DELETE http://localhost:3000/subscriptions/{{subscriptionId}}
